import Header from "@/components/Header";
import "./globals.css";
import { SessionProvider } from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Login from "@/components/Login";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <div>
              <Header />
              <Login />
            </div>
          ) : (
            <div>
              <div>
                <Header />
              </div>
              {children}
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
